[package]
name = "brainfuck"
version = "1.0.1"
edition = "2021"
authors = ["hcy <hcy347244312@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]


[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
